FIX Show 'No preview available' message for pages with no state
silverstripe/silverstripe-cms pull request #2572
Opened 2020-07-30 21:57 UTC by Cheddam

This accompanies a logic patch in the admin module to ensure that when no preview state is available for a pagetype, it renders a message stating this. Previously a broken layout would appear instead.

2020-08-03 01:39 UTC, sachajudd commented on templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
> +            <div class="icon font-icon-monitor display-1"></div>
What's the extra icon class for?

2020-09-09 03:10 UTC, emteknetnz commented on templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PreviewPanel.ss
> +            <div class="icon font-icon-monitor display-1"></div>
@Cheddam ?

2020-10-12 05:04 UTC, bergice commented
Looks good!

When toggling the view type, there is some blank margin being added to the right side:
![image](https://user-images.githubusercontent.com/541886/95707026-ec1e7e00-0cb4-11eb-9312-b655e041e79e.png)

Small suggestion, maybe the modes should just be greyed out (with tooltip explanations) as there is no reason for using them: 
![image](https://user-images.githubusercontent.com/541886/95707166-49b2ca80-0cb5-11eb-8beb-4c0de7ef382a.png)

2021-02-17 00:26 UTC, brynwhyman commented
> When toggling the view type, there is some blank margin being added to the right side:

I think we should get this resolved before merging. 

@clarkepaul what are your thoughts on disabling the 'split' and 'preview' modes in this scenario?

2021-02-17 01:42 UTC, clarkepaul commented
@brynwhyman If the issue is anything to do with the preview width we can get rid of that just for this view. 

Is there maybe a case for a person being stuck in Preview mode and not being able to navigate out into edit/split mode? If the redirect is working properly they should be redirected away but just thinking of edge cases or errors.

The mode is also set for all pages you view afterwards (unless changed manually). Not such a biggy to disable it but it would also stop people from changing between Edit and Split modes if they wished.

I would think that the contents of the dropdown just has a line of CSS conflicting or positioned outside the area. Could be as simple as applying overflow: hidden to fix the issue? I would prefer an attempt to fix the CSS first before disabling the dropdown.

2021-03-04 04:05 UTC, Cheddam commented
I can actually reproduce the weird overflow bug without these PRs present, so perhaps we can raise a separate issue to track resolving that?

2021-03-04 21:13 UTC, Cheddam commented
Have validated that the CI failure on this one is an [existing issue](https://travis-ci.com/github/silverstripe/silverstripe-cms/jobs/488334077). This PR needs to be merged before the admin one for that to go green.

2021-03-04 22:11 UTC, emteknetnz commented
@Cheddam could you reply to this [old feedback](https://github.com/silverstripe/silverstripe-cms/pull/2572/files#r464154272) before getting merged

2021-06-22 02:00 UTC, emteknetnz approved these changes

2021-06-22 05:10 UTC, emteknetnz requested changes
We'll need to add a constraint of admin ^1.8.1 (or whatever the corresponding admin tag is) otherwise this will happen when you click a regular page, then the redirector page in split view

![image](https://user-images.githubusercontent.com/4809037/122866818-b457f200-d37c-11eb-80f7-c69cdedea09a.png)

2021-06-24 00:44 UTC, maxime-rainville commented
@clarkepaul What's our view on the contrast of these colours? Is this an accessibility problem?

![image](https://user-images.githubusercontent.com/1168676/123185328-c6a36e80-d4e9-11eb-99c8-87c6966381ff.png)

2021-06-24 01:21 UTC, maxime-rainville commented
As @bergice mentioned, there's some funkiness going on when you start using the preview width feature. I also don't think this is worth fixing. Here's what it looks like for reference: https://youtu.be/VxajIPsVx7M

2021-06-28 02:30 UTC, clarkepaul commented
Happy with the fix (just got a walk through from @emteknetnz), toolbar is now fixed to the bottom, user can still switch between view modes which is a good result.

The issue of the messaging not being in the centre for the varying screen sizes which are not "Auto" can be raised as a separate issue. Will log soon.

@maxime-rainville in regards to contrast of messaging, it doesn't meet the standards so I can raise an issue for that. The icon should be at least 3:1 and the text 4.5:1. The icon could be swapped out for a SVG now and lucky the text is actually text so easy to improve.

2021-06-29 01:44 UTC, merged