UPDATE generate canonical via MetaComponents
silverstripe/silverstripe-cms pull request #2647
Opened 2021-04-01 02:16 UTC by muskie9

This replaces using the `MetaTags` method as replacing or removing a canonical requires string manipulation vs unsetting an array key, and is preferred.

Additionally, the virtual page can disable generating a canonical for the proxied page.

resolves #2637

2021-04-01 08:25 UTC, kinglozzer requested changes
Happy to merge if you can remove the `UseProxiedForCanonical` stuff 😃

2021-04-01 08:25 UTC, kinglozzer commented on code/Model/VirtualPage.php
> +        'UseProxiedForCanonical' => 'Boolean',
We can’t add this in a patch release, it’d need to be a separate PR against the `4` branch. It’d also need to be `Boolean(1)`, as `private static $defaults` doesn’t affect existing records

2021-04-06 00:55 UTC, muskie9 commented
@kinglozzer sure thing, I wondered if introducing the new field wouldn't work in the targeted branch, good to know. Let me know if there are any other changes. I'll look at adding the new field once everything is merged up to `4` if that change still makes sense.

2021-04-06 08:29 UTC, kinglozzer approved these changes
Looks good 👍

2021-05-14 20:02 UTC, dhensby commented
Sorry for being a bit out of it, but why has the method `MetaTags` been replaced with `MetaComponents`?

2021-05-14 20:33 UTC, muskie9 commented
Hi @dhensby,

The primary thought from our side was more consistent detection/replacement of the meta tags that may be generated by other modules. By implementing the canonical via the `MetaComponents()` modules simply check if the `canonical` key exists in `$tags` vs having to do a find and replace via regular expression or the like (by way of the extension points).

After looking at the methods a bit more I'd also have the opinion that `MetaComponents()` should really handle managing the components to be generated, and the `MetaTags()` method would simply assemble what is returned by `MetaComponents()`. As it stands now, both allow for manipulating the meta tags in different ways which can also cause confusion as to which extension point should be used.

The opinion of the managing vs assembling of the tags may not be valid, but was a thought I had recently so figured I'd throw it out there. When tracking down our initial issue on this I had no idea `MetaComponents()` was a method, and realized it could provide a much more consistent result if community modules utilized it as well.

Cheers!

2021-05-14 20:49 UTC, merged