API Stop using deprecated API
silverstripe/silverstripe-cms pull request #2794
Opened 2022-11-02 05:00 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/pull/10565

2022-11-07 04:14 UTC, emteknetnz commented on code/Controllers/CMSMain.php
> +     * @deprecated 4.12.0 Will be removed without equivalent functionality to replace it
Deprecating because CMSPageHistoryController is deprecated

2022-11-07 04:31 UTC, emteknetnz commented on tests/php/Tasks/MigrateSiteTreeLinkingTaskTest.php
> -    protected static $use_draft_site = true;
Removed because FunctionalTest::use_draft_site is deprecated. This never actually needed to be set true for the unit test to pass.

2022-11-09 01:16 UTC, emteknetnz commented on composer.json
> +        "silverstripe/versioned-admin": "^1.7@dev",
This is required to get CMS page history to work since we've migrated from the deprecated CMS class to the class in versioned-admin

2022-11-09 01:17 UTC, emteknetnz commented on tests/php/Search/ZZZSearchFormTest.php
> +    protected static $fixture_file = 'ZZZSearchFormTest.yml';
Renamed to remove the warning that the filename did not match the class name

2022-11-15 01:42 UTC, sabina-talipova requested changes

2022-11-15 01:42 UTC, sabina-talipova commented on tests/php/Controllers/CMSPageHistoryControllerTest.php
>  use SilverStripe\Forms\HTMLReadonlyField;
```suggestion
use SilverStripe\Forms\HTMLReadonlyField;
use SilverStripe\Control\Controller;
use SilverStripe\Core\Injector\Injector;
```

2022-11-15 01:42 UTC, sabina-talipova commented on tests/php/Controllers/CMSPageHistoryControllerTest.php
> +use SilverStripe\Dev\Deprecation;
```suggestion
use SilverStripe\Dev\Deprecation;
use SilverStripe\Dev\FunctionalTest;
```

2022-11-16 01:14 UTC, sabina-talipova approved these changes

2022-11-16 01:14 UTC, sabina-talipova commented
Require https://github.com/silverstripe/silverstripe-framework/pull/10565 to be merged.

2022-11-16 01:44 UTC, sabina-talipova commented
Build failed https://github.com/silverstripe/silverstripe-cms/actions/runs/3467505777/jobs/5809980321

2022-11-16 03:10 UTC, emteknetnz commented
@sabina-talipova green now

2022-11-16 03:13 UTC, merged