FEAT update SiteTree permissions in CMS
silverstripe/silverstripe-cms pull request #2862
Opened 2023-06-15 11:31 UTC by andrewandante

Linked to https://github.com/silverstripe/silverstripe-framework/pull/10819

Allows `SiteTree` objects to have permissions assigned to a individual users, rather than having to assign it directly to groups.

## Issue
- silverstripe/silverstripe-framework#10817

2023-06-22 10:38 UTC, andrewandante commented
This is now all working alongside the Framework PR; however, the `ViewerMembers` and `EditorMembers` fields always show in the CMS, instead of dynamically show/hide depending on the `ViewType`/`EditType`. Can't seem to pinpoint what is doing that, any tips?

i.e. Ideally they shouldn't be showing in these cases:
![image](https://github.com/silverstripe/silverstripe-cms/assets/9702648/bcfe2841-23b0-4c40-9c02-cfedc8f2eec8)

2023-07-05 01:25 UTC, GuySartorelli commented
There's a couple of PHP linting issues in CI which need to be ironed out

2023-07-05 22:17 UTC, GuySartorelli requested changes
Just one small change here, otherwise it all looks okay to me

2023-07-05 22:17 UTC, GuySartorelli commented on code/Model/SiteTree.php
> +            && \in_array($member->ID, $this->ViewerMembers()->column('ID'), true)
```suggestion
            && $this->ViewerMembers()->filter('ID', $member->ID)->count() > 0
```
Slightly more efficient, both the db query itself and not having to iterate over IDs. It won't be significant in 99% of cases, but I can imagine someone adding _all_ of the members from a large organisation into this field at some point.

2023-07-05 22:17 UTC, GuySartorelli commented on code/Model/SiteTree.php
> +            if ($this->CanViewType === InheritedPermissions::ONLY_THESE_USERS) {
Good catch on this bug 👍

2023-07-06 00:41 UTC, GuySartorelli requested changes
For some reason when I try this locally, the `Viewer Users` and `Editor Users` fields don't save. It's probably more to do with the changes you made to ListboxField than anything here, but given that's merged already I'll put the note here instead.
Can you please investigate and assuming you can reproduce this, find out where that bug's coming from? The value _is_ being passed in as part of the form submission request, I can see that from my browser.

It does work fine in react contexts - just the entwine context that's borked.

2023-07-06 04:00 UTC, andrewandante commented
> Can you please investigate and assuming you can reproduce this, find out where that bug's coming from?

Yep can reproduce, I saw it last night and have spent a decent chunk of today implementing XDebug in a new dev environment 😅 so I'll see what I can find - I think it's likely do with the validation step. Thanks for all your reviewing thus far!

2023-07-06 06:02 UTC, andrewandante commented
[This Framework commit](https://github.com/silverstripe/silverstripe-framework/pull/10819/commits/a03d0fdf684e00d388b67af6ce9bdc99877709af) I think fixes the issue - locally I now have both the entwine and react versions working 🤞

2023-07-06 21:37 UTC, GuySartorelli approved these changes
LGTM

2023-07-06 22:08 UTC, merged