ENH Use SearchableMutliDropdownField to select Members
silverstripe/silverstripe-cms pull request #2906
Opened 2023-11-23 05:01 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1618

2023-12-04 22:07 UTC, GuySartorelli requested changes
Don't forget to remove the `$membersMap` variable assignment

2023-12-08 03:26 UTC, emteknetnz commented
Have removed $membersMap variable

2023-12-11 22:01 UTC, GuySartorelli requested changes
LGTM, but needs a dependency bump for admin and framework.

2023-12-12 21:40 UTC, emteknetnz commented
Have updated composer.json

2023-12-13 00:45 UTC, GuySartorelli requested changes

2023-12-13 00:45 UTC, GuySartorelli commented on composer.json
>          "silverstripe/admin": "^2",
```suggestion
        "silverstripe/admin": "^2.2",
```

2023-12-13 01:15 UTC, emteknetnz commented on composer.json
>          "silverstripe/admin": "^2",
Updated

2023-12-13 20:55 UTC, GuySartorelli approved these changes
LGTM, will merge once admin and framework PRs are merged

2023-12-14 20:32 UTC, merged