MNT Tweak behat test to look for tag with specific attribute itstead of looking for a specifc string in the HTML
silverstripe/silverstripe-cms pull request #2971
Opened 2024-06-19 10:43 UTC by maxime-rainville

This test was failing because it was looking for a very specific string in the HTML. Just checking for a tag with a specific attribute is more reliable because it doesn't depend on the order of parameter.

## Parent issue
- https://github.com/silverstripe/.github/issues/230

2024-06-19 21:10 UTC, GuySartorelli commented on tests/behat/features/edit-a-page.feature
> +  @onlyme
```suggestion
```

2024-06-20 00:51 UTC, emteknetnz requested changes
Need to remove the `@onlyme` annotation

2024-06-26 10:15 UTC, maxime-rainville commented
Fixed my booboo.

2024-06-27 02:45 UTC, emteknetnz approved these changes

2024-06-30 22:36 UTC, merged