API Make CMSMain more generic
silverstripe/silverstripe-cms pull request #3035
Opened 2024-12-08 20:24 UTC by GuySartorelli

Replaces https://github.com/silverstripe/silverstripe-cms/pull/3017

Remove hardcoded references to pages and SiteTree
Remove assumption that records are versioned
Remove or validate assumptions about methods on the model class
Improve general architecture of CMSMain

Relies on changes in https://github.com/silverstripe/silverstripe-admin/pull/1837

## Issue
- https://github.com/silverstripe/silverstripe-cms/issues/2947

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSMain.php
> +        }
This is debatable - I've got it here mostly because I don't want to rework the UI elements that assume records can be sorted. Realistically there probably isn't much value in using this UI if your record isn't sortable anyway.

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSMain.php
> +        }
This is a little untidy but necessary for now. Will be cleared up as part of https://github.com/silverstripe/silverstripe-cms/issues/2951 which removes the `CMSMain` subclasses.

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSMain.php
> +        }
Another thing that will be tidied up as part of https://github.com/silverstripe/silverstripe-cms/issues/2951

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSMain.php
> +        }
Another thing that will be tidied up as part of https://github.com/silverstripe/silverstripe-cms/issues/2951

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSPageAddController.php
This whole class was just a couple of templates and a form. It's been moved into `CMSMainAddForm`, the associated template, and an action on `CMSMain` to get the form.

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSPagesController.php
This whole class was effectively just a placeholder to render some templates. Those templates have been distilled into `CMSMain_LeftPanel.ss` which is included in the appropriate places in `CMSMain_Content.ss` and `CMSMain_Tools.ss`

Note I'm not removing `CMSPageEditController` in this PR because it wasn't removable when the bulk of this work was done. That can be removed in https://github.com/silverstripe/silverstripe-cms/issues/2951 which has an explicit AC for that purpose.

2024-12-11 23:13 UTC, ChloeSartorelli commented on templates/SilverStripe/CMS/Controllers/Includes/CMSMain_Tools.ss
There was quite a lot of duplication between this and the old `CMSPagesController` templates. That duplication is now distilled into the `CMSMain_LeftPanel.ss` template.

2024-12-11 23:13 UTC, ChloeSartorelli commented on templates/SilverStripe/CMS/Controllers/Includes/CMSMain_PageList_Sidebar.ss
This just had a pointless include in it

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSMain.php
> -    }
Not needed - this is just basically adding an extra extension hook on top of getDefaultSearchContext().
If we think that's valuable, it should be added to `DataObject::getDefaultSearchContext()` instead - though the fact that method doesn't already have an extension hook implies one isn't needed there. People can also override `getDefaultSearchContext()` in their `Page` or other classes to return different search contexts.

2024-12-11 23:13 UTC, ChloeSartorelli commented on code/Controllers/CMSPageAddController.php
> -        }
This specific piece of code isn't replicated in the new form or action.
It was originally introduced in https://github.com/silverstripe/silverstripe-cms/commit/c247db51465973385fe2a678293d2f4a28f3b1af which doesn't really make it clear what the intended use case of it is. It doesn't seem to be needed at all, nothing that I can see sets the `Parent` key in the data array.

2024-12-12 04:09 UTC, emteknetnz approved these changes
Great work!

2024-12-12 04:09 UTC, emteknetnz requested changes
Except now there's a merge conflict! :-)

2024-12-12 04:26 UTC, emteknetnz approved these changes

2024-12-12 04:27 UTC, merged